apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: gatekeeper-operator-product-sub
spec:
  remediationAction: enforce
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: gatekeeper-operator-product
          namespace: openshift-operators
        spec:
          name: gatekeeper-operator-product
          channel: stable
          installPlanApproval: Automatic
          source: redhat-operators
          sourceNamespace: openshift-marketplace
  pruneObjectBehavior: None
