apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gatekeeper-policyset
placementBindingDefaults:
  name: gatekeeper-policyset
policyDefaults:
  consolidateManifests: true
  policyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  categories:
    - CM Configuration Management
  controls:
    - CM-2 Baseline Configuration
  namespace: policies
  remediationAction: enforce
  severity: medium
  policySets:
    - gatekeeper-policyset
  standards:
    - Container-platform-standard-v1
  namespaceSelector:
    exclude:
      - openshift-*
      - kube-*
    matchLabels:
      container-platform-managed: true
policies:
- name: pod-deny-missing-netsegment
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: input/pod-deny-missing-netsegment
- name: container-deny-latest-tag
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: input/container-deny-latest-tag
- name: container-deny-privileged-if-tenant
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: input/container-deny-privileged-if-tenant
- name: pod-deny-host-pid
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: input/pod-deny-host-pid
policySets:
  - description: A set of open policy agent gatekeeper admission controls that require best practices to be followed for applications being installed onto the managed cluster
    name: gatekeeper-policyset
    placement:
      placementPath: input/placement.yaml

