apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - managedclustersetbinding.yaml
  - clusterrolebinding.yaml
  - channel.yaml
  - placement.yaml
  - subscription.yaml
  - application.yaml
