apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: container-platform-gatekeeper
  name: container-platform
  namespace: policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'container-platform-managed-hub'
              operator: 'In'
              values:
                - 'true'
  clusterSets:
    - container-platform
