apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerDenyLatestTag
metadata:
  name: containerdenylatesttag
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - DaemonSet
      - Deployment
      - StatefulSet
    namespaceSelector:
      matchLabels:
        container-platform-managed: "true"
